# Generated by Django 5.1.7 on 2025-03-12 22:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('source', '0006_alter_source_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchCrawl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.UUID('e3fdc252-6663-4501-aa6f-b5d812ae81a6'), editable=False, unique=True)),
                ('extra', models.JSONField(blank=True, null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crawls', to='source.matchlinks')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crawls', to='source.source')),
            ],
        ),
        migrations.CreateModel(
            name='LineUpsTab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.UUID('c167b8cc-1806-45c3-a8f5-bddc23b15b35'), editable=False, unique=True)),
                ('extra', models.JSONField(blank=True, null=True)),
                ('crawl_data', models.JSONField(blank=True, null=True)),
                ('is_valid', models.BooleanField(default=False)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineups', to='crawler.matchcrawl')),
            ],
        ),
        migrations.CreateModel(
            name='IndexTab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.UUID('821e3e23-5293-4842-af7f-0eebede56774'), editable=False, unique=True)),
                ('extra', models.JSONField(blank=True, null=True)),
                ('crawl_data', models.JSONField(blank=True, null=True)),
                ('is_valid', models.BooleanField(default=False)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indexes', to='crawler.matchcrawl')),
            ],
        ),
        migrations.CreateModel(
            name='ClubTab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.UUID('ca24da58-6a12-4c3b-a94c-6f73edec2c39'), editable=False, unique=True)),
                ('extra', models.JSONField(blank=True, null=True)),
                ('crawl_data', models.JSONField(blank=True, null=True)),
                ('is_valid', models.BooleanField(default=False)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clubs', to='crawler.matchcrawl')),
            ],
        ),
        migrations.CreateModel(
            name='StatisticsTab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.UUID('931b2b7c-cc93-47e6-a3d7-accc2d25ca9d'), editable=False, unique=True)),
                ('extra', models.JSONField(blank=True, null=True)),
                ('crawl_data', models.JSONField(blank=True, null=True)),
                ('is_valid', models.BooleanField(default=False)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='crawler.matchcrawl')),
            ],
        ),
        migrations.CreateModel(
            name='TimeLineTab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.UUID('e03256d2-ba37-48fb-a741-e13dd9397669'), editable=False, unique=True)),
                ('extra', models.JSONField(blank=True, null=True)),
                ('crawl_data', models.JSONField(blank=True, null=True)),
                ('is_valid', models.BooleanField(default=False)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timelines', to='crawler.matchcrawl')),
            ],
        ),
    ]
