# Generated by Django 5.1.7 on 2025-03-13 00:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0002_remove_matchcrawl_uuid_alter_clubtab_uuid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubtab',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='lineupstab',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='statisticstab',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='timelinetab',
            name='uuid',
        ),
        migrations.AlterField(
            model_name='indextab',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('38edb919-5402-45ac-80b5-c62a8e9e7bad'), editable=False, unique=True),
        ),
    ]
