# Generated by Django 5.1.7 on 2025-03-13 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0003_remove_clubtab_uuid_remove_lineupstab_uuid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indextab',
            name='uuid',
        ),
    ]
