# Generated by Django 5.1.7 on 2025-03-14 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0005_matchcrawl_has_club_matchcrawl_has_index_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CleanData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_pk', models.CharField(blank=True, max_length=110, null=True)),
                ('title', models.CharField(blank=True, max_length=1000, null=True)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('league_name', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('statistics', models.JSONField(blank=True, null=True)),
                ('league', models.JSONField(blank=True, null=True)),
                ('related_data', models.JSONField(blank=True, null=True)),
                ('stadium', models.JSONField(blank=True, null=True)),
                ('referee', models.JSONField(blank=True, null=True)),
                ('result', models.JSONField(blank=True, null=True)),
                ('home_team', models.JSONField(blank=True, null=True)),
                ('away_team', models.JSONField(blank=True, null=True)),
                ('club', models.JSONField(blank=True, null=True)),
                ('cards', models.JSONField(blank=True, null=True)),
                ('goals', models.JSONField(blank=True, null=True)),
                ('substitutions', models.JSONField(blank=True, null=True)),
                ('match_date', models.JSONField(blank=True, null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clean_data', to='crawler.matchcrawl')),
            ],
        ),
    ]
