# Generated by Django 5.1.7 on 2025-03-14 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('source', '0014_alter_source_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=512)),
                ('url', models.CharField(max_length=512)),
                ('image', models.CharField(blank=True, max_length=512, null=True)),
                ('country', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=512)),
                ('url', models.CharField(max_length=512)),
                ('image', models.CharField(blank=True, max_length=512, null=True)),
                ('country', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Referee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('url', models.CharField(max_length=512)),
                ('assistant', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('url', models.CharField(max_length=256)),
                ('attendance', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=150)),
                ('logo', models.URLField(blank=True, null=True)),
                ('extra', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_date', models.CharField(blank=True, max_length=20, null=True)),
                ('match_time', models.CharField(blank=True, max_length=20, null=True)),
                ('match_day', models.CharField(blank=True, max_length=20, null=True)),
                ('home_score', models.IntegerField(blank=True, null=True)),
                ('away_score', models.IntegerField(blank=True, null=True)),
                ('match_id', models.CharField(blank=True, max_length=200, null=True)),
                ('url', models.CharField(max_length=256)),
                ('extra', models.JSONField(blank=True, null=True)),
                ('league', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='source.leaguelinks')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='source.leagueseasonlinks')),
                ('referee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.referee')),
                ('stadium', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.stadium')),
            ],
        ),
        migrations.CreateModel(
            name='MatchTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('home', 'Home'), ('away', 'Away'), ('other', 'Other')], max_length=50)),
                ('winner', models.BooleanField(default=False)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('goals', models.JSONField()),
                ('Manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='content.manager')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='content.match')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='content.team')),
            ],
        ),
        migrations.CreateModel(
            name='MatchTeamPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(choices=[('goalkeeper', 'Goalkeeper'), ('centre', 'Centre'), ('defensive', 'Defensive'), ('attacking', 'Attacking')], max_length=50)),
                ('match_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='content.matchteam')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='content.player')),
            ],
        ),
    ]
