# Generated by Django 5.1.7 on 2025-03-14 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchteamplayer',
            name='card',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='matchteamplayer',
            name='goal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='matchteamplayer',
            name='is_captain',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='matchteamplayer',
            name='main_player',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='matchteamplayer',
            name='market_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchteamplayer',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchteamplayer',
            name='substitutes',
            field=models.BooleanField(default=False),
        ),
    ]
