# Generated by Django 5.1.7 on 2025-03-14 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_matchteamplayer_card_matchteamplayer_goal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchteamplayer',
            name='market_value',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
