# Generated by Django 5.1.7 on 2025-03-14 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_match_away_cards_match_away_goals_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchteamplayer',
            name='number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
