# Generated by Django 5.1.7 on 2025-03-12 19:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeagueData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.UUID('a9efa8ef-cf75-4bde-8364-5228a19a4736'), editable=False, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('logo', models.URLField(blank=True, null=True)),
                ('year', models.PositiveIntegerField()),
                ('extra', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MatchData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_date', models.DateTimeField(blank=True, null=True)),
                ('home_score', models.IntegerField(blank=True, null=True)),
                ('away_score', models.IntegerField(blank=True, null=True)),
                ('sku', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('full_time_result', models.CharField(blank=True, max_length=10, null=True)),
                ('extra_time_result', models.CharField(blank=True, max_length=10, null=True)),
                ('url', models.CharField(max_length=256)),
                ('goals', models.JSONField()),
                ('cards', models.JSONField()),
                ('substitutions', models.JSONField()),
                ('extra', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RefereeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('url', models.CharField(max_length=512)),
                ('assistant', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='StadiumData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('url', models.CharField(max_length=256)),
                ('attendance', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='TeamData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.UUID('eca8197a-3475-4277-942f-ee6acfa19bcc'), editable=False, unique=True)),
                ('url', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=150)),
                ('logo', models.URLField(blank=True, null=True)),
                ('manager', models.JSONField()),
                ('player', models.JSONField()),
                ('composition', models.CharField(max_length=50)),
                ('extra', models.JSONField()),
            ],
        ),
    ]
