# Generated by Django 5.1.7 on 2025-03-12 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('match', '0001_initial'),
        ('source', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaguedata',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='league', to='source.source'),
        ),
        migrations.AddField(
            model_name='matchdata',
            name='league',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='match.leaguedata'),
        ),
        migrations.AddField(
            model_name='matchdata',
            name='referee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='match.refereedata'),
        ),
        migrations.AddField(
            model_name='matchdata',
            name='stadium',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='match.stadiumdata'),
        ),
        migrations.AddField(
            model_name='teamdata',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams', to='source.source'),
        ),
        migrations.AddField(
            model_name='matchdata',
            name='away_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='match.teamdata'),
        ),
        migrations.AddField(
            model_name='matchdata',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='match.teamdata'),
        ),
    ]
