# Generated by Django 5.1.7 on 2025-03-12 20:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaguedata',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('78a3b777-f7f8-45af-8b1e-0aa83ae4688c'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='teamdata',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('ac137192-212c-43da-b2d5-03cf165ce75e'), editable=False, unique=True),
        ),
    ]
