# Generated by Django 5.1.7 on 2025-03-12 20:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0003_alter_leaguedata_uuid_alter_teamdata_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaguedata',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('eb249746-b71f-49b2-b9a6-07993c10fc8b'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='teamdata',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('5b30f3ff-8afa-44bb-a13a-10430a7d503a'), editable=False, unique=True),
        ),
    ]
