# Generated by Django 5.1.7 on 2025-03-12 20:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0004_alter_leaguedata_uuid_alter_teamdata_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaguedata',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('e0574dd0-e2d6-400a-b960-991812caf23d'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='teamdata',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('f8a58719-9ca8-47f4-92aa-c5d42a13cee5'), editable=False, unique=True),
        ),
    ]
