# Generated by Django 5.1.7 on 2025-03-12 22:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0006_alter_leaguedata_uuid_alter_teamdata_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchdata',
            name='match_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='leaguedata',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('d35d62ad-549b-47f4-a669-5b5c1b83bddc'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='teamdata',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('115cf0e6-5e68-4a57-aad7-4ebc9b238bd0'), editable=False, unique=True),
        ),
    ]
