# Generated by Django 5.1.7 on 2025-03-12 22:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0007_matchdata_match_id_alter_leaguedata_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaguedata',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('4e1878e6-d97f-4e7d-8c30-6bc9afea32e8'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='teamdata',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('12fdc583-abba-46ea-9f8d-b8436b3b9a49'), editable=False, unique=True),
        ),
    ]
