# Generated by Django 5.1.7 on 2025-03-13 01:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0009_alter_leaguedata_uuid_alter_teamdata_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaguedata',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('03e199cc-0180-4bf1-9009-62843b4c85d9'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='teamdata',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('e22cd235-d8c0-4824-9bb1-f1df1e0a8bfb'), editable=False, unique=True),
        ),
    ]
