# Generated by Django 5.1.7 on 2025-03-13 01:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0010_alter_leaguedata_uuid_alter_teamdata_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaguedata',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('d31273b5-3b3c-4d0d-9f30-797f3b5dd599'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='teamdata',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('a4e5bf3e-edd7-4ad3-9ab4-96acc38bb39d'), editable=False, unique=True),
        ),
    ]
