# Generated by Django 5.1.7 on 2025-03-14 17:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0011_alter_leaguedata_uuid_alter_teamdata_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaguedata',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('96361c39-adea-48ed-bdb0-3345354ccb46'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='teamdata',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('ec4abe1c-f549-4b23-a8b2-f95a22a2ceb2'), editable=False, unique=True),
        ),
    ]
