# Generated by Django 5.1.7 on 2025-03-14 17:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0012_alter_leaguedata_uuid_alter_teamdata_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaguedata',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('31c3a982-6260-4862-a78d-f36287663483'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='teamdata',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('a1bf7d35-f388-4991-8d6f-c57e0f20bc57'), editable=False, unique=True),
        ),
    ]
