# Generated by Django 5.1.7 on 2025-03-14 18:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0013_alter_leaguedata_uuid_alter_teamdata_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaguedata',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('abf15f78-a0a6-45d5-9958-6bb123691d75'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='teamdata',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('98ee1a6d-edd3-44b3-9a04-fb632c57ec56'), editable=False, unique=True),
        ),
    ]
