# Generated by Django 5.1.7 on 2025-03-14 18:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0014_alter_leaguedata_uuid_alter_teamdata_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaguedata',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('907af447-675b-4a00-841a-9d93603575e1'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='teamdata',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('c00ad61b-21eb-4aaa-be14-09a10535d452'), editable=False, unique=True),
        ),
    ]
