# Generated by Django 5.1.7 on 2025-03-14 20:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0016_alter_leaguedata_uuid_alter_teamdata_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaguedata',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('d90d8ecd-d89b-4764-91f1-1992dacbb431'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='teamdata',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('784d79f0-e42c-4a81-b9c7-933ddcca4b83'), editable=False, unique=True),
        ),
    ]
