# Generated by Django 5.1.7 on 2025-03-14 20:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0017_alter_leaguedata_uuid_alter_teamdata_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaguedata',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('b831ac0b-d50c-4ced-ac66-547d7b506eb6'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='teamdata',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('b77a3429-bc66-44d4-945d-ef329bd665bf'), editable=False, unique=True),
        ),
    ]
