# Generated by Django 5.1.7 on 2025-03-14 20:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0018_alter_leaguedata_uuid_alter_teamdata_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaguedata',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('f76fb4ef-479b-4d94-bc59-566f508f3a8f'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='teamdata',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('723cae40-4978-42d7-8cb8-f6c4c4413f33'), editable=False, unique=True),
        ),
    ]
