# Generated by Django 5.1.7 on 2025-03-12 20:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0002_leaguelinks_source_alter_source_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaguelinks',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('085cdb42-f27b-4155-94fc-b478e7033847'), editable=False, unique=True),
        ),
    ]
