# Generated by Django 5.1.7 on 2025-03-12 20:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0005_alter_leaguedata_uuid_alter_teamdata_uuid'),
        ('source', '0003_leaguelinks_url_alter_source_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchlinks',
            name='match_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_link', to='match.matchdata'),
        ),
        migrations.AlterField(
            model_name='source',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('f2ff3423-0cb5-4e14-aa19-2f3e8e5bf9d5'), editable=False, unique=True),
        ),
    ]
