# Generated by Django 5.1.7 on 2025-03-12 20:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0004_alter_matchlinks_match_obj_alter_source_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchlinks',
            name='extra',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('c275ba0f-60f2-482e-8597-23dacd6a81b7'), editable=False, unique=True),
        ),
    ]
