# Generated by Django 5.1.7 on 2025-03-12 22:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0006_alter_source_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('62bd71ff-4af0-44d4-921e-ddb66edf415b'), editable=False, unique=True),
        ),
    ]
