# Generated by Django 5.1.7 on 2025-03-13 00:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0007_alter_source_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('130cadcc-5a3b-4910-8e81-d73cff5ca078'), editable=False, unique=True),
        ),
    ]
