# Generated by Django 5.1.7 on 2025-03-13 01:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0008_alter_source_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('2a667e5a-3a03-46b6-934a-bc1fa28c94c8'), editable=False, unique=True),
        ),
    ]
