# Generated by Django 5.1.7 on 2025-03-13 01:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0009_alter_source_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('93836f17-d509-4612-99b2-7da753210541'), editable=False, unique=True),
        ),
    ]
