# Generated by Django 5.1.7 on 2025-03-14 17:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0010_alter_source_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaguelinks',
            name='complete_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaguelinks',
            name='match_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('c4371c6f-22e2-4634-a4b1-c82261d8648f'), editable=False, unique=True),
        ),
    ]
