# Generated by Django 5.1.7 on 2025-03-14 17:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0011_leaguelinks_complete_count_leaguelinks_match_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaguelinks',
            name='extra',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('9284726f-d6a7-43b8-bfa1-cd44ecfebf70'), editable=False, unique=True),
        ),
    ]
