# Generated by Django 5.1.7 on 2025-03-14 18:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0012_leaguelinks_extra_alter_source_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('b0049f31-3f90-4b26-bac6-6152e6af0dde'), editable=False, unique=True),
        ),
    ]
