# Generated by Django 5.1.7 on 2025-03-14 18:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0013_alter_source_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('36479b86-7bb5-40b1-9a0c-6bfdc4db2c88'), editable=False, unique=True),
        ),
    ]
