# Generated by Django 5.1.7 on 2025-03-14 20:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0014_alter_source_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('b6c38ce7-5af3-4e58-ae19-efdb43b2a30b'), editable=False, unique=True),
        ),
    ]
