# Generated by Django 5.1.7 on 2025-03-14 20:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0015_alter_source_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('ea86c163-53cd-4dc4-a567-5a40dd6147a6'), editable=False, unique=True),
        ),
    ]
