# Generated by Django 5.1.7 on 2025-03-14 20:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0016_alter_source_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('d46b218a-19fd-4ba3-931a-332f78ff83c7'), editable=False, unique=True),
        ),
    ]
