# Generated by Django 5.1.7 on 2025-03-14 20:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0017_alter_source_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('d0d4faef-9ae5-451b-99b8-0bb58e43970a'), editable=False, unique=True),
        ),
    ]
